"""add_media_files_to_post

Revision ID: 68d26c7de2d9
Revises: 001
Create Date: 2025-10-24 12:39:21.457637+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d26c7de2d9'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_files', sa.JSON(), nullable=True, comment='List of Telegram file_id for photos/media'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'media_files')
    # ### end Alembic commands ###
