"""add_media_group_support

Revision ID: 40cbaac93134
Revises: 68d26c7de2d9
Create Date: 2025-10-24 23:26:04.801468+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cbaac93134'
down_revision: Union[str, None] = '68d26c7de2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_group_id', sa.Integer(), nullable=True, comment='Telegram grouped_id for media groups (albums)'))
    op.add_column('posts', sa.Column('message_ids', sa.JSON(), nullable=True, comment='All message_id from media group'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'message_ids')
    op.drop_column('posts', 'media_group_id')
    # ### end Alembic commands ###
